name: Build Pipeline

on:
    pull_request:
        branches: [main]
    workflow_dispatch:


jobs:
  build:
    name: job-test-name
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

